import { BookOpen, Users, BarChart3, CreditCard, Star, Zap, Shield, Globe } from "lucide-react";

export type LessonType = "video" | "text" | "quiz" | "assignment" | "download";

export const MOCK_COURSES = [
  {
    id: "1",
    title: "Complete Web Development Bootcamp",
    creator: "Sarah Chen",
    creatorAvatar: "",
    thumbnail: "",
    price: 89.99,
    originalPrice: 149.99,
    rating: 4.8,
    reviewCount: 2341,
    studentCount: 12450,
    lessonCount: 186,
    duration: "42h 30m",
    level: "Beginner" as const,
    category: "Development",
    tags: ["HTML", "CSS", "JavaScript", "React"],
    description: "Master web development from scratch. Build real projects with HTML, CSS, JavaScript, React, Node.js, and more.",
    isBestseller: true,
    isFeatured: true,
    completionRate: 78,
  },
  {
    id: "2",
    title: "Data Science & Machine Learning with Python",
    creator: "Dr. James Miller",
    creatorAvatar: "",
    thumbnail: "",
    price: 129.99,
    originalPrice: 199.99,
    rating: 4.9,
    reviewCount: 1856,
    studentCount: 8920,
    lessonCount: 234,
    duration: "56h 15m",
    level: "Intermediate" as const,
    category: "Data Science",
    tags: ["Python", "ML", "TensorFlow", "Pandas"],
    description: "Comprehensive data science course covering Python, machine learning, deep learning, and data visualization.",
    isBestseller: true,
    isFeatured: true,
    completionRate: 65,
  },
  {
    id: "3",
    title: "UI/UX Design Masterclass",
    creator: "Emily Brooks",
    creatorAvatar: "",
    thumbnail: "",
    price: 69.99,
    rating: 4.7,
    reviewCount: 1203,
    studentCount: 6780,
    lessonCount: 98,
    duration: "28h 45m",
    level: "Beginner" as const,
    category: "Design",
    tags: ["Figma", "UX Research", "Prototyping"],
    description: "Learn professional UI/UX design from scratch using Figma, design thinking, and user research methodologies.",
    isBestseller: false,
    isFeatured: true,
    completionRate: 82,
  },
  {
    id: "4",
    title: "Advanced React & TypeScript Patterns",
    creator: "Alex Nguyen",
    creatorAvatar: "",
    thumbnail: "",
    price: 99.99,
    rating: 4.9,
    reviewCount: 987,
    studentCount: 4560,
    lessonCount: 145,
    duration: "38h 20m",
    level: "Advanced" as const,
    category: "Development",
    tags: ["React", "TypeScript", "Next.js", "Testing"],
    description: "Deep dive into advanced React patterns, TypeScript generics, performance optimization, and testing strategies.",
    isBestseller: false,
    isFeatured: false,
    completionRate: 71,
  },
  {
    id: "5",
    title: "Digital Marketing Strategy",
    creator: "Maya Rodriguez",
    creatorAvatar: "",
    thumbnail: "",
    price: 59.99,
    rating: 4.6,
    reviewCount: 2100,
    studentCount: 15300,
    lessonCount: 76,
    duration: "18h 10m",
    level: "Beginner" as const,
    category: "Marketing",
    tags: ["SEO", "Social Media", "Analytics", "PPC"],
    description: "Complete digital marketing toolkit covering SEO, social media, content marketing, email campaigns, and paid ads.",
    isBestseller: true,
    isFeatured: false,
    completionRate: 85,
  },
  {
    id: "6",
    title: "iOS App Development with Swift",
    creator: "Tom Harrison",
    creatorAvatar: "",
    thumbnail: "",
    price: 109.99,
    originalPrice: 179.99,
    rating: 4.8,
    reviewCount: 876,
    studentCount: 3420,
    lessonCount: 167,
    duration: "44h 55m",
    level: "Intermediate" as const,
    category: "Development",
    tags: ["Swift", "SwiftUI", "Xcode", "iOS"],
    description: "Build professional iOS apps from scratch. Master Swift, SwiftUI, Core Data, networking, and App Store deployment.",
    isBestseller: false,
    isFeatured: false,
    completionRate: 60,
  },
];

export const CATEGORIES = [
  { name: "Development", icon: BookOpen, count: 1240 },
  { name: "Data Science", icon: BarChart3, count: 856 },
  { name: "Design", icon: Star, count: 634 },
  { name: "Marketing", icon: Globe, count: 512 },
  { name: "Business", icon: CreditCard, count: 445 },
  { name: "Photography", icon: Zap, count: 321 },
];

export const STATS = [
  { label: "Active Creators", value: "12,000+", icon: Users },
  { label: "Courses Published", value: "48,000+", icon: BookOpen },
  { label: "Students Enrolled", value: "2.1M+", icon: Globe },
  { label: "Revenue Generated", value: "$84M+", icon: CreditCard },
];

export const CREATOR_STATS = {
  totalRevenue: 47850,
  monthlyRevenue: 12340,
  totalStudents: 3245,
  activeStudents: 1876,
  totalCourses: 8,
  publishedCourses: 6,
  avgRating: 4.7,
  completionRate: 72,
  revenueData: [
    { month: "Jul", revenue: 6200 },
    { month: "Aug", revenue: 7800 },
    { month: "Sep", revenue: 9100 },
    { month: "Oct", revenue: 8400 },
    { month: "Nov", revenue: 10200 },
    { month: "Dec", revenue: 11500 },
    { month: "Jan", revenue: 12340 },
  ],
  enrollmentData: [
    { month: "Jul", enrollments: 186 },
    { month: "Aug", enrollments: 234 },
    { month: "Sep", enrollments: 298 },
    { month: "Oct", enrollments: 267 },
    { month: "Nov", enrollments: 345 },
    { month: "Dec", enrollments: 389 },
    { month: "Jan", enrollments: 412 },
  ],
  topCourses: [
    { name: "Web Dev Bootcamp", students: 1240, revenue: 18600, rating: 4.8, health: 92 },
    { name: "React Mastery", students: 890, revenue: 13350, rating: 4.9, health: 88 },
    { name: "Node.js Complete", students: 645, revenue: 9675, rating: 4.6, health: 75 },
    { name: "CSS Animations", students: 470, revenue: 7050, rating: 4.7, health: 81 },
  ],
};

export const STUDENT_COURSES = [
  { id: "1", title: "Complete Web Development Bootcamp", creator: "Sarah Chen", progress: 67, lastAccessed: "2 hours ago", totalLessons: 186, completedLessons: 125 },
  { id: "2", title: "Data Science & ML with Python", creator: "Dr. James Miller", progress: 34, lastAccessed: "1 day ago", totalLessons: 234, completedLessons: 80 },
  { id: "3", title: "UI/UX Design Masterclass", creator: "Emily Brooks", progress: 89, lastAccessed: "3 hours ago", totalLessons: 98, completedLessons: 87 },
];

export const COURSE_CURRICULUM: { id: string; title: string; lessons: { id: string; title: string; type: LessonType; duration: string; completed: boolean; isFree: boolean }[] }[] = [
  {
    id: "s1",
    title: "Getting Started",
    lessons: [
      { id: "l1", title: "Welcome & Course Overview", type: "video" as const, duration: "8:30", completed: true, isFree: true },
      { id: "l2", title: "Setting Up Your Environment", type: "video" as const, duration: "15:20", completed: true, isFree: true },
      { id: "l3", title: "Your First Project", type: "video" as const, duration: "22:45", completed: true, isFree: false },
      { id: "l4", title: "Module Quiz", type: "quiz" as const, duration: "10 min", completed: false, isFree: false },
    ],
  },
  {
    id: "s2",
    title: "HTML Fundamentals",
    lessons: [
      { id: "l5", title: "HTML Document Structure", type: "video" as const, duration: "18:15", completed: false, isFree: false },
      { id: "l6", title: "Semantic HTML Elements", type: "video" as const, duration: "24:30", completed: false, isFree: false },
      { id: "l7", title: "Forms and Inputs", type: "video" as const, duration: "28:10", completed: false, isFree: false },
      { id: "l8", title: "HTML Best Practices", type: "text" as const, duration: "12 min read", completed: false, isFree: false },
      { id: "l9", title: "Assignment: Build a Landing Page", type: "assignment" as const, duration: "45 min", completed: false, isFree: false },
    ],
  },
  {
    id: "s3",
    title: "CSS Mastery",
    lessons: [
      { id: "l10", title: "CSS Selectors Deep Dive", type: "video" as const, duration: "20:00", completed: false, isFree: false },
      { id: "l11", title: "Flexbox Layout", type: "video" as const, duration: "32:15", completed: false, isFree: false },
      { id: "l12", title: "CSS Grid", type: "video" as const, duration: "28:40", completed: false, isFree: false },
      { id: "l13", title: "Responsive Design", type: "video" as const, duration: "35:20", completed: false, isFree: false },
      { id: "l14", title: "CSS Resources Pack", type: "download" as const, duration: "—", completed: false, isFree: false },
    ],
  },
];
